replicaCount: 2

image:
  repository: analytics-engine
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 8000

ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: analytics.enterprise.com
      paths:
        - path: /
          pathType: ImplementationSpecific

resources:
  limits:
    cpu: 1000m
    memory: 1024Mi
  requests:
    cpu: 500m
    memory: 512Mi
